pvellanki@orsa01:/data/pvellanki/orsa-package-2$ python3 monthly-report.py --month 2023-10
2023-10-\d2\.db
Traceback (most recent call last):
  File "/data/pvellanki/orsa-package-2/monthly-report.py", line 59, in <module>
    result = consolidated_cursor.execute(query)
sqlite3.OperationalError: no such table: consolidated_data
