E
======================================================================
ERROR: setUpClass (__main__.TestFIXSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "fix_test_suite.py", line 27, in setUpClass
    cls.app = fix.Application()
  File "/usr/local/lib64/python3.6/site-packages/quickfix.py", line 39589, in __init__
    this = _quickfix.new_Application(_self, )
RuntimeError: accessing abstract class or protected constructor

----------------------------------------------------------------------
Ran 0 tests in 0.005s

FAILED (errors=1)
